### ISSUE TITLE
[Feat] .Net SDK 100% grpc api coverage

### ISSUE THREAD

**Issue by tomekkolo** [codenotary/immudb4net#10]
**Description**
.Net SDK must support all GRPC api.

**Action items**
- [x] All methods can be invoked with a client
- [ ] All methods that support streaming can be used
- [x] Add support for synchronous operations
- [x] SQL

**Comment by emkaminsk** [comment]
After discussion with @byo - @raducrisan1 Is there something left or can we close this one and track other features in separate tasks?

**Comment by tomekkolo** [comment]
let's close it.
